### ISSUE TITLE
Remove ConfigurationExtensions.AddTestConfiguration

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Configuration#40]
This replicates the zombie config pattern that @idg10 is trying to remove. Specifically, it loads the `local.settings.json` file _the wrong way_, encouraging all sorts of confusing wrongness.

**Comment by jamesbroome** [comment]
On closer inspection, this method is still valid in test scenarios (which are the only places that it is used). We therefore have not deleted it. Outside of the Functions host, or other applicable runtime host (i.e. when you are running Specflow tests), the local settings/config/json files are not loaded automatically so this method is still needed to manually do this.

However, the code is currently confusing as expects the local configuration file to be called `local.settings.json` which has connotations relating to the Functions host. In fact, this method has nothing to do with Functions (and all the current use cases have no concern with Azure Functions at all) so this file could have any name.

So, we have updated the method signature to require the file path of the local json config file to be specified - there is now no default, so any connotations associated with the name of the file have been removed. We have also added specs to validate that the method can successfully read in config values in both nested and flattened structures.
